# **1. Iris Flower Classification using KNN**

Dataset: Iris Dataset (UCI / Kaggle)

Dataset Link:

https://www.kaggle.com/datasets/uciml/iris

# **Tasks:**
Load the dataset using Pandas.

Separate features and target.

Split the data into training and testing sets.

Train a KNN classifier with K=3.

Predict the test set labels.

Calculate the accuracy score.

Display the Confusion Matrix.

Generate the Classification Report.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.datasets import load_wine
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score

from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
df=pd.read_csv('Iris.csv')
df.sample(10)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
60,61,5.0,2.0,3.5,1.0,Iris-versicolor
63,64,6.1,2.9,4.7,1.4,Iris-versicolor
14,15,5.8,4.0,1.2,0.2,Iris-setosa
117,118,7.7,3.8,6.7,2.2,Iris-virginica
6,7,4.6,3.4,1.4,0.3,Iris-setosa
40,41,5.0,3.5,1.3,0.3,Iris-setosa
9,10,4.9,3.1,1.5,0.1,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
56,57,6.3,3.3,4.7,1.6,Iris-versicolor
13,14,4.3,3.0,1.1,0.1,Iris-setosa

In [ ]:
df.shape

(150, 6)

In [ ]:
x=df.drop('Species',axis=1)
y=df['Species']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [ ]:
knn_model=Pipeline(
    steps=[
        ('scalar',StandardScaler()), #
        ('knn',KNeighborsClassifier(n_neighbors=3,metric='minkowski',
            p=2))
    ]
)
knn_model

Pipeline(steps=[('scalar', StandardScaler()),
                ('knn', KNeighborsClassifier(n_neighbors=3))])

In [ ]:
knn_model.fit(x_train,y_train)

Pipeline(steps=[('scalar', StandardScaler()),
                ('knn', KNeighborsClassifier(n_neighbors=3))])

In [ ]:
y_pred=knn_model.predict(x_test) # target col ta encoding kora nai
y_pred

array(['Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa'],
      dtype=object)

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]

In [ ]:
print(classification_report(y_test, y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00        10
 Iris-virginica       1.00      1.00      1.00        10

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

🔹 মূল কথা

👉 scaler কোনো “learning model” না
👉 এটা শুধু data কে একই scale-এ আনার জন্য formula based transformation

🧠 এক লাইনে মনে রাখো:

Scaler = প্রতিটা feature-এর mean & std শিখে নিয়ে সব value কে z-score এ convert করে

# **Dataset: Customer Personality Analysi**s

**Dataset Link:**

https://www.kaggle.com/datasets/imakash3011/customer-personality-analysis

**Tasks:**

Create a customer response prediction problem using the Response column.

Handle missing values.

Scale the numerical features.

Use GridSearchCV to tune:

n_neighbors

metric

weights

Report the best parameters.

Compare tuned KNN with default KNN.

Evaluate using:

Accuracy

Precision

Recall

F1-score

In [ ]:
df = pd.read_csv('marketing_campaign.csv', sep='\t')
df

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,709,...,5,0,0,0,0,0,0,3,11,0
2236,4001,1946,PhD,Together,64014.0,2,1,10-06-2014,56,406,...,7,0,0,0,1,0,0,3,11,0
2237,7270,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,908,...,6,0,1,0,0,0,0,3,11,0
2238,8235,1956,Master,Together,69245.0,0,1,24-01-2014,8,428,...,3,0,0,0,0,0,0,3,11,0
2239,9405,1954,PhD,Married,52869.0,1,1,15-10-2012,40,84,...,7,0,0,0,0,0,0,3,11,1

In [ ]:
df.isnull().sum()

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score


# Load Dataset
df = pd.read_csv('marketing_campaign.csv',sep='\t')

# Missing Value Handle
df['Income'] = df['Income'].fillna(df['Income'].median())

# Remove Unnecessary Column
df = df.drop(['ID'],axis=1)

# Encoding
df = pd.get_dummies(df,drop_first=True)

# Feature and Target
x = df.drop(['Response'],axis=1)
y = df['Response']

# Train Test Split
x_train,x_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Default KNN
knn_model = Pipeline(
    steps=[
        ('scaler',StandardScaler()),
        ('knn',KNeighborsClassifier())
    ]
)

knn_model.fit(x_train,y_train)

y_pred = knn_model.predict(x_test)

print("Default Accuracy:",
      accuracy_score(y_test,y_pred))

print("Default Precision:",
      precision_score(y_test,y_pred))

print("Default Recall:",
      recall_score(y_test,y_pred))

print("Default F1:",
      f1_score(y_test,y_pred))


# Grid Search
params = {
    'knn__n_neighbors': range(1,30),
    'knn__metric':['euclidean','manhattan','minkowski'],
    'knn__weights':['uniform','distance']
}

grid_search = GridSearchCV(
    estimator=knn_model,
    param_grid=params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_search.fit(x_train,y_train)

print("Best Parameters:")
print(grid_search.best_params_)

best_model = grid_search.best_estimator_

y_pred_best = best_model.predict(x_test)

print("Tuned Accuracy:",
      accuracy_score(y_test,y_pred_best))

print("Tuned Precision:",
      precision_score(y_test,y_pred_best))

print("Tuned Recall:",
      recall_score(y_test,y_pred_best))

print("Tuned F1:",
      f1_score(y_test,y_pred_best))

Default Accuracy: 0.8214285714285714
Default Precision: 0.21739130434782608
Default Recall: 0.07462686567164178
Default F1: 0.1111111111111111
Best Parameters:
{'knn__metric': 'manhattan', 'knn__n_neighbors': 13, 'knn__weights': 'distance'}
Tuned Accuracy: 0.8638392857142857
Tuned Precision: 0.75
Tuned Recall: 0.13432835820895522
Tuned F1: 0.22784810126582278